/**
 * Privilege elevation ("Platform Mode") for the Platform Console.
 *
 * Authentication answers "who is this?" — the platform-operator claim in
 * auth.users.app_metadata (see lib/server/platform-operator.ts). Elevation answers a
 * separate question: "may they perform privileged platform actions right now?" An
 * operator signs in normally and may see the Platform Console menu, but every
 * privileged action stays blocked until they re-authenticate against a dedicated
 * Supervisor Password that is NOT their login password.
 *
 * Design:
 *   - The supervisor password is never stored anywhere in plaintext. The server holds
 *     only a scrypt hash (PLATFORM_SUPERVISOR_SECRET_HASH), and the presented password
 *     is hashed and compared in constant time. The hash is server-only: it is never
 *     sent to the browser and never appears in an API response.
 *   - A successful elevation issues a signed, httpOnly, sameSite=strict cookie. The
 *     signing key is HKDF-derived from the stored hash, so no second secret to manage
 *     and a rotated password invalidates every outstanding elevation automatically.
 *   - The cookie has NO maxAge, making it a browser-session cookie: closing the browser
 *     ends Platform Mode, as required.
 *   - The cookie is bound to the operator's email, so it cannot be replayed against a
 *     different account, and carries an absolute expiry (default 30 minutes).
 *
 * Trade-off worth knowing: elevation state lives in the signed cookie rather than a
 * database row, so "Exit Platform Mode" revokes by clearing the cookie on the client.
 * A cookie already exfiltrated from a machine stays valid until its absolute expiry —
 * the same model GitHub/AWS sudo-mode use. The 30-minute ceiling is what bounds that
 * exposure. Server-side revocation would need a session table; sql/067 is the natural
 * home if that is wanted later.
 */

import { createHmac, hkdfSync, randomBytes, scryptSync, timingSafeEqual } from "node:crypto";

export const ELEVATION_COOKIE = "vyron_platform_elevation";
export const SUPERVISOR_SECRET_ENV = "PLATFORM_SUPERVISOR_SECRET_HASH";
export const SUPERVISOR_EMERGENCY_SECRET_ENV = "PLATFORM_SUPERVISOR_SECRET_HASH_EMERGENCY";

export const DEFAULT_ELEVATION_TTL_MINUTES = 30;
export const DEFAULT_ELEVATION_IDLE_MINUTES = 15;

/** Failed supervisor-password attempts before the operator is locked out. */
export const MAX_FAILED_ATTEMPTS = 5;
export const LOCKOUT_MINUTES = 15;

export type ElevationClaims = {
  /** Operator email the elevation is bound to. */
  sub: string;
  /** Issued-at, epoch seconds. */
  iat: number;
  /** Absolute expiry, epoch seconds. */
  exp: number;
  /** Which configured secret was used — surfaced in the audit trail. */
  via: "primary" | "emergency";
  /** Random per-session id, so two elevations are never byte-identical. */
  jti: string;
};

export type ElevationReason =
  | "absent"
  | "malformed"
  | "bad_signature"
  | "expired"
  | "wrong_operator"
  /** Terminated from Active Platform Sessions, or by an emergency lockdown (sql/067).
   * Applied on top of token verification — see lib/platform/elevation-registry.ts. */
  | "revoked";

export type ElevationState =
  | { elevated: true; claims: ElevationClaims; secondsRemaining: number }
  | { elevated: false; reason: ElevationReason };

function stripEnvQuotes(value: string): string {
  const t = value.trim();
  if (
    t.length >= 2 &&
    ((t.startsWith('"') && t.endsWith('"')) || (t.startsWith("'") && t.endsWith("'")))
  ) {
    return t.slice(1, -1).trim();
  }
  return t;
}

function readEnv(name: string): string {
  return stripEnvQuotes(process.env[name] || "");
}

function positiveIntEnv(name: string, fallback: number): number {
  const raw = Number(readEnv(name));
  return Number.isFinite(raw) && raw > 0 ? Math.floor(raw) : fallback;
}

export function elevationTtlMinutes(): number {
  return positiveIntEnv("PLATFORM_ELEVATION_TTL_MINUTES", DEFAULT_ELEVATION_TTL_MINUTES);
}

export function elevationIdleMinutes(): number {
  return positiveIntEnv("PLATFORM_ELEVATION_IDLE_MINUTES", DEFAULT_ELEVATION_IDLE_MINUTES);
}

// ---------------------------------------------------------------------------
// Supervisor password hashing (scrypt)
// ---------------------------------------------------------------------------

/**
 * Stored format: scrypt:N:r:p:<saltBase64>:<hashBase64>
 * Generated by scripts/generate-supervisor-secret.mjs.
 *
 * Colon-separated rather than the more conventional `$` because this value lives in
 * .env files: Next.js runs dotenv-expand, which treats `$N` as a variable reference
 * and silently rewrites a `$`-delimited hash into garbage. Base64 never contains a
 * colon, so this delimiter is unambiguous and survives every shell and env loader.
 */
const SCRYPT_PREFIX = "scrypt";
const FIELD_SEPARATOR = ":";
const KEY_LENGTH = 64;

export function hashSupervisorPassword(
  password: string,
  options?: { N?: number; r?: number; p?: number; salt?: Buffer }
): string {
  const N = options?.N ?? 16384;
  const r = options?.r ?? 8;
  const p = options?.p ?? 1;
  const salt = options?.salt ?? randomBytes(16);
  // maxmem must be raised above the default 32MB for N=16384, r=8.
  const derived = scryptSync(password, salt, KEY_LENGTH, { N, r, p, maxmem: 256 * 1024 * 1024 });
  return [SCRYPT_PREFIX, N, r, p, salt.toString("base64"), derived.toString("base64")].join(
    FIELD_SEPARATOR
  );
}

/** Constant-time verification of a presented password against a stored scrypt hash. */
export function verifySupervisorPassword(password: string, stored: string): boolean {
  if (!password || !stored) return false;

  const parts = stored.split(FIELD_SEPARATOR);
  if (parts.length !== 6 || parts[0] !== SCRYPT_PREFIX) return false;

  const N = Number(parts[1]);
  const r = Number(parts[2]);
  const p = Number(parts[3]);
  if (!Number.isFinite(N) || !Number.isFinite(r) || !Number.isFinite(p)) return false;

  let salt: Buffer;
  let expected: Buffer;
  try {
    salt = Buffer.from(parts[4], "base64");
    expected = Buffer.from(parts[5], "base64");
  } catch {
    return false;
  }
  if (salt.length === 0 || expected.length === 0) return false;

  let actual: Buffer;
  try {
    actual = scryptSync(password, salt, expected.length, { N, r, p, maxmem: 256 * 1024 * 1024 });
  } catch {
    return false;
  }

  return actual.length === expected.length && timingSafeEqual(actual, expected);
}

export type SupervisorSecretConfig =
  | { ok: true; primary: string; emergency: string | null }
  | { ok: false; message: string };

/**
 * Reads the configured supervisor secrets. Fail-closed: with nothing configured,
 * elevation is impossible rather than open.
 */
export function getSupervisorSecrets(): SupervisorSecretConfig {
  const primary = readEnv(SUPERVISOR_SECRET_ENV);
  if (!primary) {
    return {
      ok: false,
      message: `Platform Mode is not configured. Set ${SUPERVISOR_SECRET_ENV} on the server (npm run platform:supervisor-secret).`,
    };
  }
  if (!primary.startsWith(`${SCRYPT_PREFIX}${FIELD_SEPARATOR}`)) {
    return {
      ok: false,
      message: `${SUPERVISOR_SECRET_ENV} must be a scrypt hash, not a plaintext password. Generate one with: npm run platform:supervisor-secret`,
    };
  }
  const emergency = readEnv(SUPERVISOR_EMERGENCY_SECRET_ENV);
  return {
    ok: true,
    primary,
    emergency: emergency.startsWith(`${SCRYPT_PREFIX}${FIELD_SEPARATOR}`) ? emergency : null,
  };
}

/** Returns which configured secret matched, or null. Both are always checked so the
 * response time does not reveal whether an emergency secret is configured. */
export function matchSupervisorSecret(
  password: string,
  config: { primary: string; emergency: string | null }
): "primary" | "emergency" | null {
  const primaryOk = verifySupervisorPassword(password, config.primary);
  const emergencyOk = config.emergency ? verifySupervisorPassword(password, config.emergency) : false;
  if (primaryOk) return "primary";
  if (emergencyOk) return "emergency";
  return null;
}

// ---------------------------------------------------------------------------
// Signed elevation cookie
// ---------------------------------------------------------------------------

function signingKey(secretHash: string): Buffer {
  // Derived from the stored hash: rotating the supervisor password changes this key,
  // which invalidates every outstanding elevation cookie for free.
  return Buffer.from(
    hkdfSync("sha256", Buffer.from(secretHash, "utf8"), Buffer.from("vyron-elevation-v1"), Buffer.from("cookie-signing"), 32)
  );
}

function base64url(input: Buffer | string): string {
  return Buffer.from(input).toString("base64url");
}

export function issueElevationToken(claims: ElevationClaims, secretHash: string): string {
  const payload = base64url(JSON.stringify(claims));
  const mac = createHmac("sha256", signingKey(secretHash)).update(payload).digest("base64url");
  return `${payload}.${mac}`;
}

export function buildElevationClaims(email: string, via: "primary" | "emergency"): ElevationClaims {
  const now = Math.floor(Date.now() / 1000);
  return {
    sub: email.trim().toLowerCase(),
    iat: now,
    exp: now + elevationTtlMinutes() * 60,
    via,
    jti: randomBytes(12).toString("base64url"),
  };
}

/**
 * Verifies an elevation cookie: signature, expiry, and that it belongs to the
 * currently authenticated operator. `expectedEmail` is the email from the already
 * validated auth session — binding to it stops a cookie from one account being
 * replayed against another.
 */
export function verifyElevationToken(
  token: string | undefined | null,
  expectedEmail: string,
  secretHash: string
): ElevationState {
  if (!token) return { elevated: false, reason: "absent" };

  const dot = token.lastIndexOf(".");
  if (dot <= 0) return { elevated: false, reason: "malformed" };

  const payload = token.slice(0, dot);
  const mac = token.slice(dot + 1);

  const expectedMac = createHmac("sha256", signingKey(secretHash)).update(payload).digest("base64url");
  const macBuf = Buffer.from(mac);
  const expectedBuf = Buffer.from(expectedMac);
  if (macBuf.length !== expectedBuf.length || !timingSafeEqual(macBuf, expectedBuf)) {
    return { elevated: false, reason: "bad_signature" };
  }

  let claims: ElevationClaims;
  try {
    claims = JSON.parse(Buffer.from(payload, "base64url").toString("utf8")) as ElevationClaims;
  } catch {
    return { elevated: false, reason: "malformed" };
  }

  if (!claims?.sub || !Number.isFinite(claims.exp)) {
    return { elevated: false, reason: "malformed" };
  }

  // Only compared after the signature check, so this never leaks anything an
  // attacker could not already forge.
  if (claims.sub !== expectedEmail.trim().toLowerCase()) {
    return { elevated: false, reason: "wrong_operator" };
  }

  const secondsRemaining = claims.exp - Math.floor(Date.now() / 1000);
  if (secondsRemaining <= 0) return { elevated: false, reason: "expired" };

  return { elevated: true, claims, secondsRemaining };
}

export function elevationCookieOptions() {
  return {
    httpOnly: true,
    // No maxAge on purpose: a browser-session cookie ends Platform Mode when the
    // browser closes, which is one of the required auto-lock triggers.
    sameSite: "strict" as const,
    secure: process.env.NODE_ENV === "production",
    path: "/",
  };
}

// ---------------------------------------------------------------------------
// Failed-attempt throttling
// ---------------------------------------------------------------------------

type AttemptRecord = { failures: number; lockedUntil: number };
const attempts = new Map<string, AttemptRecord>();

/**
 * Per-operator lockout after repeated wrong passwords.
 *
 * In-memory, so it is per server instance and resets on redeploy — on serverless it
 * throttles rather than guarantees. It is a speed bump on top of the real defences
 * (scrypt's cost, a high-entropy generated secret, and the audit trail); a durable
 * counter would need a database table.
 */
export function checkAttemptLock(key: string): { locked: true; retryAfterSeconds: number } | { locked: false } {
  const record = attempts.get(key);
  if (!record) return { locked: false };
  const now = Date.now();
  if (record.lockedUntil > now) {
    return { locked: true, retryAfterSeconds: Math.ceil((record.lockedUntil - now) / 1000) };
  }
  if (record.lockedUntil && record.lockedUntil <= now) attempts.delete(key);
  return { locked: false };
}

export function recordFailedAttempt(key: string): { locked: boolean; failures: number } {
  const record = attempts.get(key) || { failures: 0, lockedUntil: 0 };
  record.failures += 1;
  if (record.failures >= MAX_FAILED_ATTEMPTS) {
    record.lockedUntil = Date.now() + LOCKOUT_MINUTES * 60 * 1000;
    record.failures = 0;
    attempts.set(key, record);
    return { locked: true, failures: MAX_FAILED_ATTEMPTS };
  }
  attempts.set(key, record);
  return { locked: false, failures: record.failures };
}

export function clearFailedAttempts(key: string): void {
  attempts.delete(key);
}
